services:
  update-subscription-panel:
    image: update-subscription-panel:latest
    container_name: update-subscription-panel-container
    expose:
      - 3000
    environment:
      SUB_TOKEN: "${SUB_TOKEN}"
      ADMIN_TOKEN: "${ADMIN_TOKEN}"
      PORT: "${PORT}"